/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Smart Neo OpenAPI
 */
import { customFetch } from './custom-fetch';
export interface SmartNeoChatCompletionsArguments {
  content?: string;
}

export type chatCompletionsResponseDefault = {
  data: string;
  status: number;
};

export type chatCompletionsResponseComposite = chatCompletionsResponseDefault;

export type chatCompletionsResponse = chatCompletionsResponseComposite & {
  headers: Headers;
};

export const getChatCompletionsUrl = () => {
  return `/smart-neo/chat/completions`;
};

export const chatCompletions = async (
  smartNeoChatCompletionsArguments: SmartNeoChatCompletionsArguments,
  options?: RequestInit
): Promise<chatCompletionsResponse> => {
  return customFetch<chatCompletionsResponse>(getChatCompletionsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(smartNeoChatCompletionsArguments)
  });
};
